[libdefaults]
    default_realm = AGTPS.NET
    dns_lookup_realm = false
    dns_lookup_kdc = true
    rdns = false
    forwardable = true
    udp_preference_limit = 1
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}

[realms]
    AGTPS.NET = {
        kdc = 172.16.16.5
        admin_server = 172.16.16.5
    }

[domain_realm]
    .agtps.net = AGTPS.NET
    agtps.net = AGTPS.NET
