import {
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CheckCircle2,
  CloudDownload,
  Database,
  FileText,
  FolderTree,
  Globe,
  GraduationCap,
  Headphones,
  HeartPulse,
  House,
  LockKeyhole,
  Mail,
  MonitorCog,
  MapPin,
  Network,
  Activity,
  PanelsTopLeft,
  Plane,
  Puzzle,
  ShieldCheck,
  Settings,
  Users,
  Utensils,
  WalletCards,
  type LucideIcon,
} from "lucide-react";

export const portalIconMap: Record<string, LucideIcon> = {
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CheckCircle2,
  CloudDownload,
  Database,
  FileText,
  FolderTree,
  Globe,
  GraduationCap,
  Headphones,
  HeartPulse,
  House,
  LockKeyhole,
  Mail,
  MapPin,
  MonitorCog,
  Network,
  Activity,
  PanelsTopLeft,
  Plane,
  Puzzle,
  ShieldCheck,
  Settings,
  Users,
  Utensils,
  WalletCards,
};

export const portalIconOptions = [
  { value: "MonitorCog", label: "سامانه" },
  { value: "CheckCircle2", label: "سالم" },
  { value: "Database", label: "دیتابیس" },
  { value: "WalletCards", label: "مالی" },
  { value: "Users", label: "کاربران" },
  { value: "FileText", label: "مستندات" },
  { value: "CloudDownload", label: "دانلود" },
  { value: "ShieldCheck", label: "امنیت" },
  { value: "Globe", label: "وب" },
  { value: "Plane", label: "ارتباط" },
  { value: "BriefcaseBusiness", label: "اداری" },
  { value: "Headphones", label: "پشتیبانی" },
  { value: "HeartPulse", label: "خدمات" },
  { value: "Utensils", label: "رفاهی" },
  { value: "Mail", label: "ایمیل" },
  { value: "CalendarDays", label: "تقویم" },
  { value: "Building2", label: "ساختمان" },
  { value: "GraduationCap", label: "آموزش" },
  { value: "Puzzle", label: "ماژول" },
  { value: "Activity", label: "وضعیت" },
];

export function isUploadedIcon(value?: string | null) {
  return Boolean(value && (/^https?:\/\//.test(value) || value.startsWith("/")));
}
