resolver 127.0.0.11 valid=10s ipv6=off;

upstream agtps_api {
  zone agtps_api 64k;
  server api:3002 resolve;
}

upstream agtps_web {
  zone agtps_web 64k;
  server web:3001 resolve;
}

server {
  listen 80;
  server_name _;

  client_max_body_size 2048m;

  location /api/ {
    proxy_pass http://agtps_api/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /uploads/ {
    proxy_pass http://agtps_web/uploads/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location / {
    proxy_pass http://agtps_web;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
