ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mobile" TEXT;
ALTER TABLE "DirectoryUser" ADD COLUMN IF NOT EXISTS "mobile" TEXT;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "requireUserEmail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Setting" ADD COLUMN IF NOT EXISTS "requireUserMobile" BOOLEAN NOT NULL DEFAULT false;
